---
title: "Innleiing"
output: 
  html_document: 
    toc: true
    toc_float: true
---

"Statistikk-delen" av faget handlar eigentleg om to ting: *sannsynsrekning* og *statistikk*. I delen om sannsynsrekning tar vi for oss dei mest grunnleggande omgrepa, og ser litt på

* Aksiom for sannsyn
* Mengdelære
* Stokastiske variable
* Fordelingar

I delen om statistikk tar vi for oss 

* estimering av parametre i fordelingar
* testing av hypoteser om disse parametrane

## Sannsynlighet

Sjølv om faget heiter "*Statistikk* og landmåling" så må vi ha litt om sannsynlighet i starten. I og med at vi ikkje veit *eksakt kva feil* som ligg i ei måling så må vi sei noko om *sannsynligheten* for at feilen er stor eller lita.



## Statistikk

Faget statistikk handla mykje om å samle inn data, og så sei noko på bakgrunn av disse data. Eit svært enkelt døme er: "Kor langt er det mellom to hus?" Ein måte å avgjere dette på er gjennom følgjande prosedyre:

1. Bestem *kva avstand* som skal målast
2. Bestem *korleis* ein skal måle avstanden
3. Gjennomfør $n$ målingar $X_1$, $X_2$, ..., $X_n$ og finn gjennomsnittet $$\overline{X}=\frac{1}{n}\sum_{i=1}^n X_i$$ 

Ved å legge målingane (heretter kalt "data") inn i **R** kan dette gi
```{r}
x <- c(5.5, 5.6, 5.6, 5.4, 5.5);
avstand <- mean(x);
x
avstand
```


