---
title: "Innleiing"
output: 
  html_document: 
    toc: true
    toc_float: true
---

# Analyse av data (inferens)

Det er to viktige sider ved analyse av data:

    1. Estimering av parametre i ein valgt modell
    2. Test av hypoteser om disse parametrane

## Estimering av parametre

Dei to viktigaste parametrane vi estimerer er *forventinga* (ved gjennomsnittet $\overline{X}$) og *standardavviket* (ved empirisk standardavvik $S$).

### Forventing $\mu$

Det er to måtar å rekne denne ut på; anten ved hjelp av rådata (`svar`), eller ved å bruke det klassedelte materialet:

**Alternativ 1:** Summer alle svar og del på talet på svar:

    gjennomsnitt = sum(svar)/length(svar)

eller endå enklare med den innebygde kommandoen

    gjennomsnitt = mean(svar)

**Alternativ 2:** Grunnformelen for gjennomsnitt er
$$\overline{X}=\frac{1}{n}\sum_{i=1}^n x_i$$
    som vi kan rekne ut slik:

    gjennomsnitt = sum(svar)/length(svar)

**Alternativ 3:** For å lære litt meir om korleis Scilab sine kommandoar  kan vi også rekne ut gjennomsnittet ved å bruke frekvenstabellen:
    $$\overline{X} = \sum_{i=1}^n x_i\cdot f_i.$$
    Vi har $x_i$ i variabelen `klasser`, og $f_i$ kan vi lage i variabelen `frekvens` ved å dele `antal` på talet observasjonar:

    frekvensar = antal/length(svar)

For å multiplisere to lister med tal parvis kan vi bruke operatoren `.*`:

    klasser.*frekvensar

og summere disse:

    gjennomsnitt = sum(klasser.*frekvensar)
    
#### De store talls lov

Ein viktig ting er at eit gjennomsnitt utrekna på bakgrunn av *få* observasjonar ikkje gir eit så trygt resultat som eitt basert på *mange* observasjonar. Som døme tar vi utgangspunkt i lista pver årstal når studentane er fødde (den er samla i lista `aar`). Den gir eit gjennomsnitt på 

    mean(aar) -> 1994.14
     
Men dersom vi berre tar eit (tilfeldig) utval på $n = 5$ av disse får vi eit anna gjennomsnitt:

    mean(samwr(5, 1, aar)) -> 1995.6
    
Vi kan lett vise at kvar einaste gong vi tar ut eit *lite* utval og ser på snittet av disse, så vil dette variere frå utval til utval. Men dess større utval vi tar, dess mindre vil disse gjennomsnitta variere. Og tar vi som ektremtilfellet *alle* i utvalet så vil det ikkje vere variasjon i det heile :-)

    x = 1:100
    y1 = mean(samwr(5, 100, aar), 1)  // lag gjennomsnitt av kvart av dei 100 utvala
    y2 = mean(samwr(50, 100, aar), 1) // lag gjennomsnitt av kvart av dei 100 utvala
    plot(x,y1,'b*', x,y2)             // lag eit plot med stjerner for ei serie og linjer for den andre
    
Det er ein liten moral her: "Size matters".

### Standardavvik $\sigma$

Det beste estimatet for standardavvik får vi ved å rekne direkte på rådata:

    S = stdev(svar)

Ein alternativ måte bruker formelen som er oppgitt i læreboka:
    $$S = \sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i-\mu)^2}=\sqrt{\frac{\sum_{i=1}^n (x_i-\mu)^2}{n-1}}$$
    Denne ser avskrekkande ut, men utrekninga kan tene som eit døme på bruk av Scilab. Vi starter med å definere $n$ som talet på observasjonar (altså lengda av vektoren):

    n = length(svar)

Kvadrata av differansane kan vi finne som

(svar - gjennomsnitt).^2

men vi er mest interessert i summen av disse:

    sum((svar - gjennomsnitt).^2)

som vi deler på $n-1$ (og tar kvadratrota av):

    S = sqrt(sum((svar - gjennomsnitt).^2)/(n-1))

Men som sagt; det er enklare å bruke den innebygde kommandoen `stdev(svar)`.
